import localFont from "next/font/local";
import "./globals.css";
import { AuthProvider } from "./Providers";
import { getServerSession } from "next-auth";
import { authOptions } from "../app/conf/auth";
import { redirect } from "next/navigation";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({ children }) {
  const session = await getServerSession(authOptions);
  console.log(session,"session")

  if (!session) {
    redirect("/");
  }
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
       <AuthProvider>
        {children}
       </AuthProvider>
      </body>
    </html>
  );
}
